package main

func main() {
	persons := [[{"mal_id":118,"url":"https://myanimelist.net/people/118/Hiroshi_Kamiya","name":"Hiroshi Kamiya","image_url":"https://cdn.myanimelist.net/images/voiceactors/1/58597.jpg","language":"","member_favorites":79303},{"mal_id":52,"url":"https://myanimelist.net/people/52/Emiri_Katou","name":"Emiri Katou","image_url":"https://cdn.myanimelist.net/images/voiceactors/2/12722.jpg","language":"","member_favorites":2207},{"mal_id":28,"url":"https://myanimelist.net/people/28/Yui_Horie","name":"Yui Horie","image_url":"https://cdn.myanimelist.net/images/voiceactors/2/55669.jpg","language":"","member_favorites":15048},{"mal_id":99,"url":"https://myanimelist.net/people/99/Miyuki_Sawashiro","name":"Miyuki Sawashiro","image_url":"https://cdn.myanimelist.net/images/voiceactors/1/54600.jpg","language":"","member_favorites":37046},{"mal_id":185,"url":"https://myanimelist.net/people/185/Kana_Hanazawa","name":"Kana Hanazawa","image_url":"https://cdn.myanimelist.net/images/voiceactors/3/57913.jpg","language":"","member_favorites":86443},{"mal_id":61,"url":"https://myanimelist.net/people/61/Chiwa_Saito","name":"Chiwa Saito","image_url":"https://cdn.myanimelist.net/images/voiceactors/1/44265.jpg","language":"","member_favorites":10553}],[{"mal_id":11297,"url":"https://myanimelist.net/people/11297/Inori_Minase","name":"Inori Minase","image_url":"https://cdn.myanimelist.net/images/voiceactors/3/60752.jpg","language":"","member_favorites":14294},{"mal_id":6996,"url":"https://myanimelist.net/people/6996/Ayana_Taketatsu","name":"Ayana Taketatsu","image_url":"https://cdn.myanimelist.net/images/voiceactors/1/54669.jpg","language":"","member_favorites":7827},{"mal_id":185,"url":"https://myanimelist.net/people/185/Kana_Hanazawa","name":"Kana Hanazawa","image_url":"https://cdn.myanimelist.net/images/voiceactors/3/57913.jpg","language":"","member_favorites":86443},{"mal_id":11622,"url":"https://myanimelist.net/people/11622/Ayane_Sakura","name":"Ayane Sakura","image_url":"https://cdn.myanimelist.net/images/voiceactors/2/60754.jpg","language":"","member_favorites":10848},{"mal_id":24413,"url":"https://myanimelist.net/people/24413/Miku_Itou","name":"Miku Itou","image_url":"https://cdn.myanimelist.net/images/voiceactors/2/58504.jpg","language":"","member_favorites":1688},{"mal_id":11817,"url":"https://myanimelist.net/people/11817/Yoshitsugu_Matsuoka","name":"Yoshitsugu Matsuoka","image_url":"https://cdn.myanimelist.net/images/voiceactors/2/40132.jpg","language":"","member_favorites":28883}]];
	fmt.Println(persons.length)
	for _, p := range(persons) {
		fmt.Println(p.length)
	}
	}
}
